import { CSSObject, CSSInterpolation, Interpolation } from '@mui/system';
import { PopperClassKey } from '../../../layout/Popper';
import { ComponentsPropsList } from './props';
import { AccordionActionsClassKey } from '../../../surfaces/AccordionActions';
import { AccordionClassKey } from '../../../surfaces/Accordion';
import { AccordionDetailsClassKey } from '../../../surfaces/AccordionDetails';
import { AccordionSummaryClassKey } from '../../../surfaces/AccordionSummary';
import { AlertClassKey } from '../Alert';
import { AlertTitleClassKey } from '../AlertTitle';
import { AppBarClassKey } from '../../../surfaces/AppBar';
import { AutocompleteClassKey } from '../../../form/Autocomplete';
import { AvatarClassKey } from '../../../data-display/Avatar';
import { AvatarGroupClassKey } from '../../../data-display/AvatarGroup';
import { BackdropClassKey } from '../Backdrop';
import { BadgeClassKey } from '../../../data-display/Badge';
import { BottomNavigationActionClassKey } from '../../../navigation/BottomNavigationAction';
import { BottomNavigationClassKey } from '../../../navigation/BottomNavigation';
import { BreadcrumbsClassKey } from '../../../navigation/Breadcrumbs';
import { ButtonBaseClassKey } from '../../../form/ButtonBase';
import { ButtonClassKey } from '../../../form/Button';
import { ButtonGroupClassKey } from '../../../button/ButtonGroup';
import { CardActionAreaClassKey } from '../../../surfaces/CardActionArea';
import { CardActionsClassKey } from '../../../surfaces/CardActions';
import { CardClassKey } from '../../../surfaces/Card';
import { CardContentClassKey } from '../../../surfaces/CardContent';
import { CardHeaderClassKey } from '../../../surfaces/CardHeader';
import { CardMediaClassKey } from '../../../surfaces/CardMedia';
import { CheckboxClassKey } from '../../../form/Checkbox';
import { ChipClassKey } from '../../../data-display/Chip';
import { CircularProgressClassKey } from '../../../feedback/CircularProgress';
import { CollapseClassKey } from '../../../utils/Collapse';
import { ContainerClassKey } from '../../../layout/Container';
import { DialogActionsClassKey } from '../DialogActions';
import { DialogClassKey } from '../Dialog';
import { DialogContentClassKey } from '../DialogContent';
import { DialogContentTextClassKey } from '../DialogContentText';
import { DialogTitleClassKey } from '../DialogTitle';
import { DividerClassKey } from '../../../data-display/Divider';
import { DrawerClassKey } from '../Drawer';
import { FabClassKey } from '../../../form/Fab';
import { FilledInputClassKey } from '../../../form/FilledInput';
import { FormControlClassKey } from '../../../form/FormControl';
import { FormControlLabelClassKey } from '../../../form/FormControlLabel';
import { FormGroupClassKey } from '../../../form/FormGroup';
import { FormHelperTextClassKey } from '../../../form/FormHelperText';
import { FormLabelClassKey } from '../../../form/FormLabel';
import { GridLegacyClassKey } from '../GridLegacy';
import { GridClassKey } from '../../../layout/Grid';
import { IconButtonClassKey } from '../../../form/IconButton';
import { IconClassKey } from '../../../data-display/Icon';
import { ImageListClassKey } from '../../../data-display/ImageList';
import { ImageListItemBarClassKey } from '../../../data-display/ImageListItemBar';
import { ImageListItemClassKey } from '../../../data-display/ImageListItem';
import { InputAdornmentClassKey } from '../../../form/InputAdornment';
import { InputBaseClassKey } from '../../../form/InputBase';
import { InputClassKey } from '../../../form/Input';
import { InputLabelClassKey } from '../../../form/InputLabel';
import { LinearProgressClassKey } from '../../../feedback/LinearProgress';
import { LinkClassKey } from '../../../navigation/Link';
import { ListClassKey } from '../../../data-display/List';
import { ListItemAvatarClassKey } from '../../../data-display/ListItemAvatar';
import { ListItemClassKey } from '../../../data-display/ListItem';
import { ListItemButtonClassKey } from 'docs/data-display/ListItemButton';
import { ListItemIconClassKey } from '../../../data-display/ListItemIcon';
import { ListItemSecondaryActionClassKey } from '../../../data-display/ListItemSecondaryAction';
import { ListItemTextClassKey } from '../../../data-display/ListItemText';
import { ListSubheaderClassKey } from '../../../data-display/ListSubheader';
import { MenuClassKey } from '../../../menu/Menu';
import { MenuItemClassKey } from '../../../menu/MenuItem';
import { MenuListClassKey } from '../../../menu/MenuList';
import { MobileStepperClassKey } from '../../../navigation/MobileStepper';
import { ModalClassKey } from '../Modal';
import { NativeSelectClassKey } from '../../../form/NativeSelect';
import { OutlinedInputClassKey } from '../../../form/OutlinedInput';
import { PaginationClassKey } from '../../../pagination/Pagination';
import { PaginationItemClassKey } from '../../../pagination/PaginationItem';
import { PaperClassKey } from '../../../surfaces/Paper';
import { PopoverClassKey } from '../../../modal/Popover';
import { RadioClassKey } from '../../../form/Radio';
import { RadioGroupClassKey } from '../../../form/RadioGroup';
import { RatingClassKey } from '../../../form/Rating';
import { ScopedCssBaselineClassKey } from '../ScopedCssBaseline';
import { SelectClassKey } from '../../../form/Select';
import { SkeletonClassKey } from '../../../feedback/Skeleton';
import { SliderClassKey } from '../../../form/Slider';
import { SnackbarClassKey } from '../../../feedback/Snackbar';
import { SnackbarContentClassKey } from '../../../feedback/SnackbarContent';
import { SpeedDialClassKey } from '../../../navigation/SpeedDial';
import { SpeedDialActionClassKey } from '../../../navigation/SpeedDialAction';
import { SpeedDialIconClassKey } from '../../../navigation/SpeedDialIcon';
import { StackClassKey } from '../Stack';
import { StepButtonClasskey } from '../../../navigation/StepButton';
import { StepClasskey } from '../../../navigation/Step';
import { StepConnectorClasskey } from '../../../navigation/StepConnector';
import { StepContentClasskey } from '../../../navigation/StepContent';
import { StepIconClasskey } from '../StepIcon';
import { StepLabelClasskey } from '../../../navigation/StepLabel';
import { StepperClasskey } from '../../../navigation/Stepper';
import { SvgIconClassKey } from '../../../data-display/SvgIcon';
import { SwitchClassKey } from '../Switch';
import { TabClassKey } from '../Tab';
import { TableBodyClassKey } from '../TableBody';
import { TableCellClassKey } from '../TableCell';
import { TableClassKey } from '../Table';
import { TableContainerClassKey } from '../TableContainer';
import { TableFooterClassKey } from '../TableFooter';
import { TableHeadClassKey } from '../TableHead';
import { TablePaginationClassKey } from '../TablePagination';
import { TablePaginationActionsClassKey } from '../TablePaginationActions';
import { TableRowClassKey } from '../TableRow';
import { TableSortLabelClassKey } from '../TableSortLabel';
import { TabsClassKey } from '../Tabs';
import { TextFieldClassKey } from '../TextField';
import { ToggleButtonClassKey } from '../../../button/ToggleButton';
import { ToggleButtonGroupClassKey } from '../../../button/ToggleButtonGroup';
import { ToolbarClassKey } from '../../../surfaces/Toolbar';
import { TooltipClassKey } from '../../../data-display/Tooltip';
import { TouchRippleClassKey } from '../../../form/ButtonBase/TouchRipple';
import { TypographyClassKey } from '../../../data-display/Typography';

export type OverridesStyleRules<
  ClassKey extends string = string,
  ComponentName = keyof ComponentsPropsList,
  Theme = unknown,
> = Record<
  ClassKey,
  Interpolation<
    // Record<string, unknown> is for other props that the slot receive internally
    // Documenting all ownerStates could be a huge work, let's wait until we have a real needs from developers.
    (ComponentName extends keyof ComponentsPropsList
      ? ComponentsPropsList[ComponentName] &
          Record<string, unknown> & {
            ownerState: ComponentsPropsList[ComponentName] & Record<string, unknown>;
          }
      : {}) & {
      theme: Theme;
    } & Record<string, unknown>
  >
>;

export type ComponentsOverrides<Theme = unknown> = {
  [Name in keyof ComponentNameToClassKey]?: Partial<
    OverridesStyleRules<ComponentNameToClassKey[Name], Name, Theme>
  >;
} & {
  MuiCssBaseline?: CSSObject | string | ((theme: Theme) => CSSInterpolation);
};

export interface ComponentNameToClassKey {
  MuiAlert: AlertClassKey;
  MuiAlertTitle: AlertTitleClassKey;
  MuiAppBar: AppBarClassKey;
  MuiAutocomplete: AutocompleteClassKey;
  MuiAvatar: AvatarClassKey;
  MuiAvatarGroup: AvatarGroupClassKey;
  MuiBackdrop: BackdropClassKey;
  MuiBadge: BadgeClassKey;
  MuiBottomNavigation: BottomNavigationClassKey;
  MuiBottomNavigationAction: BottomNavigationActionClassKey;
  MuiBreadcrumbs: BreadcrumbsClassKey;
  MuiButton: ButtonClassKey;
  MuiButtonBase: ButtonBaseClassKey;
  MuiButtonGroup: ButtonGroupClassKey;
  MuiCard: CardClassKey;
  MuiCardActionArea: CardActionAreaClassKey;
  MuiCardActions: CardActionsClassKey;
  MuiCardContent: CardContentClassKey;
  MuiCardHeader: CardHeaderClassKey;
  MuiCardMedia: CardMediaClassKey;
  MuiCheckbox: CheckboxClassKey;
  MuiChip: ChipClassKey;
  MuiCircularProgress: CircularProgressClassKey;
  MuiCollapse: CollapseClassKey;
  MuiContainer: ContainerClassKey;
  MuiDialog: DialogClassKey;
  MuiDialogActions: DialogActionsClassKey;
  MuiDialogContent: DialogContentClassKey;
  MuiDialogContentText: DialogContentTextClassKey;
  MuiDialogTitle: DialogTitleClassKey;
  MuiDivider: DividerClassKey;
  MuiDrawer: DrawerClassKey;
  MuiAccordion: AccordionClassKey;
  MuiAccordionActions: AccordionActionsClassKey;
  MuiAccordionDetails: AccordionDetailsClassKey;
  MuiAccordionSummary: AccordionSummaryClassKey;
  MuiFab: FabClassKey;
  MuiFilledInput: FilledInputClassKey;
  MuiFormControl: FormControlClassKey;
  MuiFormControlLabel: FormControlLabelClassKey;
  MuiFormGroup: FormGroupClassKey;
  MuiFormHelperText: FormHelperTextClassKey;
  MuiFormLabel: FormLabelClassKey;
  MuiGridLegacy: GridLegacyClassKey;
  MuiGrid: GridClassKey;
  MuiIcon: IconClassKey;
  MuiIconButton: IconButtonClassKey;
  MuiImageList: ImageListClassKey;
  MuiImageListItem: ImageListItemClassKey;
  MuiImageListItemBar: ImageListItemBarClassKey;
  MuiInput: InputClassKey;
  MuiInputAdornment: InputAdornmentClassKey;
  MuiInputBase: InputBaseClassKey;
  MuiInputLabel: InputLabelClassKey;
  MuiLinearProgress: LinearProgressClassKey;
  MuiLink: LinkClassKey;
  MuiList: ListClassKey;
  MuiListItem: ListItemClassKey;
  MuiListItemButton: ListItemButtonClassKey;
  MuiListItemAvatar: ListItemAvatarClassKey;
  MuiListItemIcon: ListItemIconClassKey;
  MuiListItemSecondaryAction: ListItemSecondaryActionClassKey;
  MuiListItemText: ListItemTextClassKey;
  MuiListSubheader: ListSubheaderClassKey;
  MuiMenu: MenuClassKey;
  MuiMenuItem: MenuItemClassKey;
  MuiMenuList: MenuListClassKey;
  MuiMobileStepper: MobileStepperClassKey;
  MuiModal: ModalClassKey;
  MuiNativeSelect: NativeSelectClassKey;
  MuiOutlinedInput: OutlinedInputClassKey;
  MuiPagination: PaginationClassKey;
  MuiPaginationItem: PaginationItemClassKey;
  MuiPaper: PaperClassKey;
  MuiPopover: PopoverClassKey;
  MuiPopper: PopperClassKey;
  MuiRadio: RadioClassKey;
  MuiRadioGroup: RadioGroupClassKey;
  MuiRating: RatingClassKey;
  MuiScopedCssBaseline: ScopedCssBaselineClassKey;
  MuiSelect: SelectClassKey;
  MuiSkeleton: SkeletonClassKey;
  MuiSlider: SliderClassKey;
  MuiSnackbar: SnackbarClassKey;
  MuiSnackbarContent: SnackbarContentClassKey;
  MuiSpeedDial: SpeedDialClassKey;
  MuiSpeedDialAction: SpeedDialActionClassKey;
  MuiSpeedDialIcon: SpeedDialIconClassKey;
  MuiStack: StackClassKey;
  MuiStep: StepClasskey;
  MuiStepButton: StepButtonClasskey;
  MuiStepConnector: StepConnectorClasskey;
  MuiStepContent: StepContentClasskey;
  MuiStepIcon: StepIconClasskey;
  MuiStepLabel: StepLabelClasskey;
  MuiStepper: StepperClasskey;
  MuiSvgIcon: SvgIconClassKey;
  MuiSwitch: SwitchClassKey;
  MuiTab: TabClassKey;
  MuiTable: TableClassKey;
  MuiTableBody: TableBodyClassKey;
  MuiTableCell: TableCellClassKey;
  MuiTableContainer: TableContainerClassKey;
  MuiTableFooter: TableFooterClassKey;
  MuiTableHead: TableHeadClassKey;
  MuiTablePagination: TablePaginationClassKey;
  MuiTablePaginationActions: TablePaginationActionsClassKey;
  MuiTableRow: TableRowClassKey;
  MuiTableSortLabel: TableSortLabelClassKey;
  MuiTabs: TabsClassKey;
  MuiTextField: TextFieldClassKey;
  MuiToggleButton: ToggleButtonClassKey;
  MuiToggleButtonGroup: ToggleButtonGroupClassKey;
  MuiToolbar: ToolbarClassKey;
  MuiTooltip: TooltipClassKey;
  MuiTouchRipple: TouchRippleClassKey;
  MuiTypography: TypographyClassKey;
}
